package com.example.austin.masterdater;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CALENDAR_EVENT.
 */
public class CalendarEvent {

    private Long id;
    private String Name;
    private java.util.Date Date;
    private Integer Time;
    private Boolean Free;

    public CalendarEvent() {
    }

    public CalendarEvent(Long id) {
        this.id = id;
    }

    public CalendarEvent(Long id, String Name, java.util.Date Date, Integer Time, Boolean Free) {
        this.id = id;
        this.Name = Name;
        this.Date = Date;
        this.Time = Time;
        this.Free = Free;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

    public Integer getTime() {
        return Time;
    }

    public void setTime(Integer Time) {
        this.Time = Time;
    }

    public Boolean getFree() {
        return Free;
    }

    public void setFree(Boolean Free) {
        this.Free = Free;
    }

}
