package com.example.austin.masterdater;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CALENDAR_EVENT.
 */
public class CalendarEvent {

    private String Name;
    private java.util.Date Date;
    private int Time;
    private boolean Free;

    public CalendarEvent() {
    }

//    public CalendarEvent(Long id) {
//        this.id = id;
//    }

    public CalendarEvent(String Name, java.util.Date Date, int Time, boolean Free) {
        this.Name = Name;
        this.Date = Date;
        this.Time = Time;
        this.Free = Free;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

    public int getTime() {
        return Time;
    }

    public void setTime(int Time) {
        this.Time = Time;
    }

    public boolean getFree() {
        return Free;
    }

    public void setFree(boolean Free) {
        this.Free = Free;
    }

}
