package com.cs407_android.masterdater;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.cs407_android.masterdater.CalendarEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CALENDAR_EVENT.
*/
public class CalendarEventDao extends AbstractDao<CalendarEvent, Void> {

    public static final String TABLENAME = "CALENDAR_EVENT";

    public static class Properties {
        public final static Property Id = new Property(0, Integer.class, "Id", false, "ID");
        public final static Property Date = new Property(1, java.util.Date.class, "Date", false, "DATE");
        public final static Property Time = new Property(2, Integer.class, "Time", false, "TIME");
        public final static Property Free = new Property(3, Boolean.class, "Free", false, "FREE");
    };

    private Query<CalendarEvent> user_CalendarEventListQuery;

    public CalendarEventDao(DaoConfig config) {
        super(config);
    }
    
    public CalendarEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'CALENDAR_EVENT' (" + //
                "'ID' INTEGER," + // 0: Id
                "'DATE' INTEGER," + // 1: Date
                "'TIME' INTEGER," + // 2: Time
                "'FREE' INTEGER);"; // 3: Free
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CALENDAR_EVENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CalendarEvent entity) {
        stmt.clearBindings();
 
        Integer Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        java.util.Date Date = entity.getDate();
        if (Date != null) {
            stmt.bindLong(2, Date.getTime());
        }
 
        Integer Time = entity.getTime();
        if (Time != null) {
            stmt.bindLong(3, Time);
        }
 
        Boolean Free = entity.getFree();
        if (Free != null) {
            stmt.bindLong(4, Free ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public CalendarEvent readEntity(Cursor cursor, int offset) {
        CalendarEvent entity = new CalendarEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // Date
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // Time
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // Free
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CalendarEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setFree(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected Void updateKeyAfterInsert(CalendarEvent entity, long rowId) {
        // TODO XXX Only Long PKs are supported currently
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(CalendarEvent entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "calendarEventList" to-many relationship of User. */
    public synchronized List<CalendarEvent> _queryUser_CalendarEventList(Integer Id) {
        if (user_CalendarEventListQuery == null) {
            QueryBuilder<CalendarEvent> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.Id.eq(Id));
            user_CalendarEventListQuery = queryBuilder.build();
        } else {
            user_CalendarEventListQuery.setParameter(0, Id);
        }
        return user_CalendarEventListQuery.list();
    }

}
