package com.cs407_android.masterdater;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CALENDAR_EVENT.
 */
public class CalendarEvent {

    private Integer Id;
    private java.util.Date Date;
    private Integer Time;
    private Boolean Free;

    public CalendarEvent() {
    }

    public CalendarEvent(Integer Id, java.util.Date Date, Integer Time, Boolean Free) {
        this.Id = Id;
        this.Date = Date;
        this.Time = Time;
        this.Free = Free;
    }

    public Integer getId() {
        return Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

    public Integer getTime() {
        return Time;
    }

    public void setTime(Integer Time) {
        this.Time = Time;
    }

    public Boolean getFree() {
        return Free;
    }

    public void setFree(Boolean Free) {
        this.Free = Free;
    }

}
